# Generated by Django 5.0 on 2024-01-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('job', models.CharField(max_length=300)),
            ],
        ),
    ]
