# Generated by Django 5.0 on 2024-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_say'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(max_length=300)),
                ('img', models.ImageField(upload_to='index/img')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(max_length=300)),
                ('img', models.ImageField(upload_to='index/img')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
